/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionTools: typeof import('./src/components/ToolsLayer/ActionTools/index.vue')['default']
    AttributePosition: typeof import('./src/components/ToolsLayer/ActionTools/AttributePosition/index.vue')['default']
    AttributePostion: typeof import('./src/components/ToolsLayer/ActionTools/AttributePostion.vue')['default']
    CanvasList: typeof import('./src/components/ToolsLayer/CanvasList/index.vue')['default']
    Drag: typeof import('./src/components/ToolsLayer/LayerButton/Drag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Export: typeof import('./src/components/ToolsLayer/Export/index.vue')['default']
    GraphicEditorRender: typeof import('./src/components/GraphicEditorRender/index.vue')['default']
    Layer: typeof import('./src/components/ToolsLayer/Layer/index.vue')['default']
    LayerButton: typeof import('./src/components/ToolsLayer/LayerButton/index.vue')['default']
    Layout: typeof import('./src/components/ToolsLayer/Layout/index.vue')['default']
    Panel: typeof import('./src/components/ToolsLayer/Panel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapePanel: typeof import('./src/components/ToolsLayer/Panel/ShapePanel/index.vue')['default']
    TextPanel: typeof import('./src/components/ToolsLayer/Panel/TextPanel/index.vue')['default']
    TextPannel: typeof import('./src/components/ToolsLayer/Panel/TextPannel/index.vue')['default']
    Title: typeof import('./src/components/ToolsLayer/Title/index.vue')['default']
    ToolsLayer: typeof import('./src/components/ToolsLayer/index.vue')['default']
  }
}

// For TSX support
declare global {
  const ActionTools: typeof import('./src/components/ToolsLayer/ActionTools/index.vue')['default']
  const AttributePosition: typeof import('./src/components/ToolsLayer/ActionTools/AttributePosition/index.vue')['default']
  const AttributePostion: typeof import('./src/components/ToolsLayer/ActionTools/AttributePostion.vue')['default']
  const CanvasList: typeof import('./src/components/ToolsLayer/CanvasList/index.vue')['default']
  const Drag: typeof import('./src/components/ToolsLayer/LayerButton/Drag.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Export: typeof import('./src/components/ToolsLayer/Export/index.vue')['default']
  const GraphicEditorRender: typeof import('./src/components/GraphicEditorRender/index.vue')['default']
  const Layer: typeof import('./src/components/ToolsLayer/Layer/index.vue')['default']
  const LayerButton: typeof import('./src/components/ToolsLayer/LayerButton/index.vue')['default']
  const Layout: typeof import('./src/components/ToolsLayer/Layout/index.vue')['default']
  const Panel: typeof import('./src/components/ToolsLayer/Panel/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ShapePanel: typeof import('./src/components/ToolsLayer/Panel/ShapePanel/index.vue')['default']
  const TextPanel: typeof import('./src/components/ToolsLayer/Panel/TextPanel/index.vue')['default']
  const TextPannel: typeof import('./src/components/ToolsLayer/Panel/TextPannel/index.vue')['default']
  const Title: typeof import('./src/components/ToolsLayer/Title/index.vue')['default']
  const ToolsLayer: typeof import('./src/components/ToolsLayer/index.vue')['default']
}